source 'https://rubygems.org'

#gem 'byebug', group: [:development, :test]
gem 'byebug'
gem 'pry-byebug'
gem 'json'
gem 'rspec'
#gem 'json-schema', :git => 'https://github.com/GrooveStomp/json-schema', :branch => 'error-messages'
gem 'activerecord'
gem 'activesupport'
gem 'rake',         '10.4.2'
gem 'sequel',       '4.22.0'
gem 'mysql2',       '0.3.18'
gem 'selenium-webdriver'
#'2.53.3'
